#IMAGEN BASE
FROM golang:alpine
#Copiado del fuente a la nueva imagen
COPY ./nTrabajador1.go ./nTrabajador1.go 
#exponer los puertos
EXPOSE 9002
#poner en ejecución el algoritmo
CMD ["go","run","nTrabajador1.go"]